### ISSUE TITLE
Errors with relative path in kube config file

### ISSUE THREAD

**Issue by mcinquin** [golgoth31/multiShellKonfig#8]
Hi,

I recently reinstall my laptop and create a kube config file with relative path for certificate and key files.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: certs/dev/kube2_ca.pem
    server: https://127.0.0.1:6443
  name: dev-cluster
contexts:
- context:
    cluster: dev-cluster
    namespace: kube-system
    user: dev-kube-admin-ca-dev
  name: dev-kube-admin-ca-dev
current-context: dev-kube-admin-ca-dev
kind: Config
preferences: {}
users:
- name: dev-kube-admin-ca-dev
  user:
    client-certificate: certs/dev/kube2_kube-admin-ca-dev.pem
    client-key: certs/dev/kube2_kube-admin-ca-dev.key
```

msk will then search for these files in its context directory.

```
# kubectx dev-kube-admin-ca-dev@\~/.kube/config

# kgp
Error in configuration:
* unable to read client-cert /home/user/.kube/msk/contexts/ck6r9q5brhb3lp8cp12g/12220285d3e0f2393d1223298d99effd3b6cf1d1baa61f8c6296016f68f36082/certs/dev/kube2_kube-admin-ca-dev.pem for dev-kube-admin-ca-dev due to open /home/user/.kube/msk/contexts/ck6r9q5brhb3lp8cp12g/12220285d3e0f2393d1223298d99effd3b6cf1d1baa61f8c6296016f68f36082/certs/dev/kube2_kube-admin-ca-dev.pem: no such file or directory
* unable to read client-key /home/user/.kube/msk/contexts/ck6r9q5brhb3lp8cp12g/12220285d3e0f2393d1223298d99effd3b6cf1d1baa61f8c6296016f68f36082/certs/dev/kube2_kube-admin-ca-dev.key for dev-kube-admin-ca-dev due to open /home/user/.kube/msk/contexts/ck6r9q5brhb3lp8cp12g/12220285d3e0f2393d1223298d99effd3b6cf1d1baa61f8c6296016f68f36082/certs/dev/kube2_kube-admin-ca-dev.key: no such file or directory
* unable to read certificate-authority /home/user/.kube/msk/contexts/ck6r9q5brhb3lp8cp12g/12220285d3e0f2393d1223298d99effd3b6cf1d1baa61f8c6296016f68f36082/certs/dev/kube2_ca.pem for dev-cluster due to open /home/user/.kube/msk/contexts/ck6r9q5brhb3lp8cp12g/12220285d3e0f2393d1223298d99effd3b6cf1d1baa61f8c6296016f68f36082/certs/dev/kube2_ca.pem: no such file or directory

```

Regards.
